#ifndef TSFHACK_HPP
#define TSFHACK_HPP

#ifdef SWIGTYPE_p_TSFExtended__VectorTypeT_double_t
#ifndef SWIGTYPE_p_TSFExtended__VectorTypeTdouble_t

#define SWIGTYPE_p_TSFExtended__VectorTypeTdouble_t SWIGTYPE_p_TSFExtended__VectorTypeT_double_t 

#endif
#endif
#endif
