#! /bin/sh

if [ "$SPKG_LOCAL" = "" ]; then
   echo "SPKG_LOCAL undefined ... exiting";
   echo "Maybe run 'qsnake --shell'?"
   exit 1
fi


set -e

mkdir -p bin-dir
cd bin-dir

cmake \
    -D CMAKE_INSTALL_PREFIX="$SPKG_LOCAL" \
    -D CMAKE_BUILD_TYPE=DEBUG \
    -D CMAKE_C_FLAGS="-fPIC -Wl,-V" \
    -D CMAKE_CXX_FLAGS="-fPIC -Wl,-V" \
    -D CMAKE_Fortran_FLAGS="-fPIC" \
    -D Trilinos_ENABLE_PyTrilinos=OFF \
    -D BUILD_SHARED_LIBS=ON \
    -D Trilinos_ENABLE_ALL_PACKAGES=OFF \
    -D Trilinos_ENABLE_Thyra=OFF \
    -D Trilinos_ENABLE_TESTS=OFF \
    -D Trilinos_ENABLE_NOX=ON \
    -D Trilinos_ENABLE_MPI=OFF \
    -D DART_TESTING_TIMEOUT=600 \
    -D BLAS_LIBRARY_DIRS="$SPKG_LOCAL/lib" \
    -D LAPACK_LIBRARY_DIRS="$SPKG_LOCAL/lib" \
    -D BLAS_LIBRARY_NAMES="blas;gfortran" \
    ..
